spring.application.name=user-service

server.servlet.context-path=/users
server.port = 9020

jwt.secretKey = asdfladf98a7df89aysf8d9yavighviuytvugvudhfa98sdfyaisuhdfa98sfy

spring.datasource.url=jdbc:postgresql://user-db:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update

#eureka config
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
